#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Install node modules
echo "Installing Node packages"
pnpm i

# Install `{{cookiecutter.package_name}}` and all dependencies
echo "Installing Python dependencies"
pip install -e ".[dev,doc,test]"
