# https://github.com/psf/black
[tool.black]
line-length = 88

# https://github.com/PyCQA/isort
[tool.isort]
known_local_folder = ["{{cookiecutter.package_name}}"]
lines_after_imports = 2
profile = "black"
skip_gitignore = true

# ruff
# - pycodestyle
# - pydocstyle
# - pyupgrade
# - flake8
# - - mccabe

# pylama
# - radon ?
# - eradicate
# - vulture
# - pylint ?

# bandit
