# https://github.com/psf/black
[tool.black]
line-length = 88

# black
# isort

# ruff
# - pycodestyle
# - pydocstyle
# - pyupgrade
# - flake8
# - - mccabe

# pylama
# - radon ?
# - eradicate
# - vulture
# - pylint ?

# bandit
